# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Zoltan Burgermeiszter - PHP Developer
email: zoltan@burgermeiszter.com
author: Zoltan Burgermeiszter
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.burgermeiszter.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github:
  username:  zburgermeiszter
  repo: zburgermeiszter.github.io

blog:
  footer:
    author:
      image: "/images/avatar/zoltan.burgermeiszter.jpg"
      description: >
        Cloud Developer, Linux, Docker and VoIP fanatic. Always looking for innovative technologies to make things faster, cheaper, easier.

# Build settings
markdown: kramdown

include: [.nojekyll, .gitignore]
exclude: [build.sh, serve.sh]

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      permalink: /blog/:title/

category_archive:
  path: /blog/categories
  slugify: true

tag_dir: /blog/tags

compress_html:
  comments: all